/** TypeRacer phrase pool — tech + desi */
export const GAME_PHRASES = [
  'yaar sun bhai',
  'jugad engineering',
  'chai piyo code karo',
  'MAX connectivity online',
  'deploy kar diya production pe',
  'bhai error kya aa raha hai',
  'socket disconnect ho gaya',
  'meme bhej de group mein',
  'react state update nahi ho raha',
  'mongodb connection timeout',
  'push notification allow kar',
  'dark mode best mode',
  'git pull kar le pehle',
  'merge conflict solve kar',
  'api response slow hai',
  'nginx reverse proxy setup',
  'docker compose up kar',
  'typescript types strict rakho',
  'nextjs page reload ho gaya',
  'tailwind class bhool gaya',
  'bollywood reference mandatory',
  'tollywood trailer better',
  'hyderabad biryani supreme',
  'bangalore traffic legendary',
  'mumbai local train survival',
  'delhi metro rush hour',
  'chennai filter coffee strong',
  'pune ganesh festival vibes',
  'kolkata rosogolla debate',
  'jaipur pink city sunset',
  'startup pitch deck ready',
  'vc meeting kal hai',
  'burn rate control karo',
  'product market fit mil gaya',
  'user retention badh raha',
  'analytics dashboard dekho',
  'A/B test chal raha',
  'SEO keywords optimize karo',
  'CDN cache hit ratio',
  'SSL certificate renew karo',
  'two factor auth enable',
  'password manager use karo',
  'phishing email mat kholo',
  'standup meeting nine baje',
  'sprint planning monday',
  'code review pending hai',
  'pair programming karte hain',
  'rubber duck debugging',
  'stack overflow copy paste',
  'chatGPT se help li',
  'vibe coding session start',
];

export default GAME_PHRASES;
